FROM python:3.10-slim

WORKDIR /app

COPY requirements-serving.txt .
RUN pip install --no-cache-dir -r requirements-serving.txt

COPY Streamlit/ /app/Streamlit/
# Streamlit will need to know the API URL via environment variable later
COPY api/ /app/api/

EXPOSE 8501

CMD ["streamlit", "run", "Streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]